import { PermitTypeDefinition, PermitTypeId } from './types/permit';

export const PERMIT_TYPES_REGISTRY: Record<PermitTypeId, PermitTypeDefinition> = {
  HOT_WORK: {
    id: 'HOT_WORK',
    label: 'Hot Work',
    code: 'HW',
    description: 'Any work involving open flames, sparks, welding, grinding, or heat generation near flammable atmospheres or combustible materials.',
    badgeColor: 'text-amber-700 bg-amber-100 border-amber-300',
    borderColor: 'border-amber-500',
    bgLightColor: 'bg-amber-50',
    iconName: 'Flame',
    defaultHazards: [
      'Flammable gas / vapor release',
      'Sparks / slag ignition of combustible material',
      'Toxic fume inhalation',
      'Flash burn / radiant heat injury',
      'Explosion risk near pressurized / chemical lines',
    ],
    defaultPrecautions: [
      'Combustible materials removed or covered within 10 meters radius',
      'Dedicated Fire Watch assigned with immediate continuous monitoring',
      'Appropriate pressurized Fire Extinguisher inspected & positioned at point of work',
      'Gas atmospheric testing verified safe (< 1% LEL, 19.5% - 23.5% O2) before striking torch',
      'Surrounding sewers, drains, and pipe openings sealed or blanketed',
      'Post-work fire watch maintained for 60 minutes after hot work finishes',
    ],
    fields: [
      {
        name: 'hotWorkType',
        label: 'Type of Hot Work',
        type: 'select',
        required: true,
        options: [
          { label: 'Arc / TIG / MIG Welding', value: 'welding' },
          { label: 'Abrasive Cutting / Grinding', value: 'grinding' },
          { label: 'Oxy-Fuel Flame Cutting', value: 'cutting' },
          { label: 'Brazing / Soldering', value: 'soldering' },
        ],
      },
      {
        name: 'fireWatchAssigned',
        label: 'Dedicated Fire Watch Personnel Name',
        type: 'text',
        required: true,
        placeholder: 'e.g. R. Murugan (Badge #FW-204)',
        helperText: 'Must remain stationed with fire extinguisher for duration of work and 60 min post-work',
      },
      {
        name: 'fireExtinguisherType',
        label: 'Fire Extinguisher Type Present at Site',
        type: 'select',
        required: true,
        options: [
          { label: 'DCP (Dry Chemical Powder - ABC)', value: 'DCP' },
          { label: 'CO2 (Carbon Dioxide - B & C)', value: 'CO2' },
          { label: 'AFFF Mechanical Foam', value: 'Foam' },
          { label: 'Pressurized Water Type', value: 'Water' },
        ],
      },
      {
        name: 'combustiblesClearedRadiusMeters',
        label: 'Combustibles Cleared / Shielded Radius (Meters)',
        type: 'number',
        required: true,
        unit: 'meters',
        placeholder: '10',
        helperText: 'Standard minimum safe clearance is 10 meters or fire-blanket shielded',
      },
      {
        name: 'gasTestReadings',
        label: 'Atmospheric Gas Test Readings (Mandatory Prior to Ignition)',
        type: 'nested_group',
        required: true,
        nestedFields: [
          {
            name: 'lelPercent',
            label: 'Combustible Gas (% LEL)',
            type: 'number',
            required: true,
            unit: '% LEL',
            placeholder: '0',
            helperText: 'Must be 0% (Strictly < 1% LEL allowed)',
          },
          {
            name: 'o2Percent',
            label: 'Oxygen Concentration (% O2)',
            type: 'number',
            required: true,
            unit: '% O2',
            placeholder: '20.9',
            helperText: 'Safe human range is 19.5% to 23.5%',
          },
          {
            name: 'testTime',
            label: 'Test Timestamp',
            type: 'text',
            required: true,
            placeholder: 'YYYY-MM-DD HH:MM',
          },
          {
            name: 'testerName',
            label: 'Certified Gas Tester Name',
            type: 'text',
            required: true,
            placeholder: 'e.g. K. Sundar (Safety Analyst)',
          },
        ],
      },
    ],
  },

  CONFINED_SPACE: {
    id: 'CONFINED_SPACE',
    label: 'Confined Space Entry',
    code: 'CSE',
    description: 'Entry into any enclosed or partially enclosed space not intended for human occupancy (vessels, tanks, boilers, silos, trenches, pits, pipelines).',
    badgeColor: 'text-purple-700 bg-purple-100 border-purple-300',
    borderColor: 'border-purple-500',
    bgLightColor: 'bg-purple-50',
    iconName: 'Box',
    defaultHazards: [
      'Oxygen deficiency (< 19.5%) or enrichment (> 23.5%)',
      'Toxic gas accumulation (H2S, CO, solvent vapors)',
      'Engulfment in liquid, grain, or bulk solid',
      'Restricted ingress / egress preventing quick evacuation',
      'Thermal extremes or mechanical agitation',
    ],
    defaultPrecautions: [
      'Positive mechanical isolation (blanks / blinds installed, lines drained and tagged)',
      'Electrical LOTO applied to all internal agitators and pumps',
      'Continuous forced ventilation operating prior to and throughout entry',
      'Multi-gas detector calibrated and running continuous 4-gas monitoring',
      'Standby attendant stationed continuously outside entrance with communication device',
      'Emergency retrieval tripod, harness, and certified rescue plan established',
      'Strict entry/exit accountability log maintained at hatchway',
    ],
    fields: [
      {
        name: 'spaceId',
        label: 'Confined Space Identifier / Vessel Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. TK-401-A (Storage Vessel 401)',
      },
      {
        name: 'entryPoint',
        label: 'Designated Entry Point / Manway',
        type: 'text',
        required: true,
        placeholder: 'e.g. Manway MW-02 (South Side Top Flange)',
      },
      {
        name: 'standbyAttendantName',
        label: 'Designated Standby Attendant (Hatch Watch)',
        type: 'text',
        required: true,
        placeholder: 'e.g. V. Krishnan (Certified Safety Attendant)',
        helperText: 'Attendant must NEVER leave entry hatch while personnel are inside',
      },
      {
        name: 'ventilationMethod',
        label: 'Ventilation Method',
        type: 'select',
        required: true,
        options: [
          { label: 'Continuous Forced Air Blower (Positive Pressure)', value: 'forced_air' },
          { label: 'Exhaust Extraction (Negative Pressure)', value: 'exhaust' },
          { label: 'Natural Cross-Flow Ventilation (Low Risk Pits Only)', value: 'natural' },
        ],
      },
      {
        name: 'rescuePlan',
        label: 'Emergency Rescue & Evacuation Plan Reference',
        type: 'text',
        required: true,
        placeholder: 'e.g. SOP-SAF-CSE-09 (Tripod + Winch + Emergency Breathing Apparatus)',
      },
      {
        name: 'atmosphericTest',
        label: 'Pre-Entry Multi-Gas Atmospheric Test',
        type: 'nested_group',
        required: true,
        nestedFields: [
          {
            name: 'o2Percent',
            label: 'Oxygen (O2)',
            type: 'number',
            required: true,
            unit: '%',
            placeholder: '20.9',
            helperText: 'Safe threshold: 19.5% - 23.5%',
          },
          {
            name: 'lelPercent',
            label: 'Combustibles (LEL)',
            type: 'number',
            required: true,
            unit: '% LEL',
            placeholder: '0',
            helperText: 'Must be 0%',
          },
          {
            name: 'h2sPpm',
            label: 'Hydrogen Sulfide (H2S)',
            type: 'number',
            required: true,
            unit: 'ppm',
            placeholder: '0',
            helperText: 'OSHA PEL: < 10 ppm',
          },
          {
            name: 'coPpm',
            label: 'Carbon Monoxide (CO)',
            type: 'number',
            required: true,
            unit: 'ppm',
            placeholder: '0',
            helperText: 'OSHA PEL: < 25 ppm',
          },
          {
            name: 'testTime',
            label: 'Test Recorded At',
            type: 'text',
            required: true,
            placeholder: 'YYYY-MM-DD HH:MM',
          },
        ],
      },
    ],
  },

  WORKING_AT_HEIGHT: {
    id: 'WORKING_AT_HEIGHT',
    label: 'Working at Height',
    code: 'WAH',
    description: 'Any work where a person could fall a distance of 1.8 meters or more, including work on roofs, scaffolds, elevated platforms, ladders, or pipe racks.',
    badgeColor: 'text-blue-700 bg-blue-100 border-blue-300',
    borderColor: 'border-blue-500',
    bgLightColor: 'bg-blue-50',
    iconName: 'ArrowUpRight',
    defaultHazards: [
      'Falls from elevation causing critical or fatal injury',
      'Dropped tools or materials striking workers below',
      'Structural collapse of scaffold or access equipment',
      'Contact with overhead electrical lines or crane runways',
      'Adverse weather (high winds > 25 knots, rain, slippery surfaces)',
    ],
    defaultPrecautions: [
      'Full body harness with dual shock-absorbing lanyards (100% tie-off)',
      'Certified anchor points (> 22.2 kN rating) verified and tagged before use',
      'Scaffold inspected by competent person with Green Tag displayed',
      'Safety barricades, warning tape, and "Danger: Overhead Work" signage below',
      'Tool lanyards and tethering bags secured to prevent dropped objects',
      'Wind speed checked (< 20 km/h) and no lightning warning in effect',
    ],
    fields: [
      {
        name: 'heightInMeters',
        label: 'Maximum Working Height (Meters)',
        type: 'number',
        required: true,
        unit: 'meters',
        placeholder: '4.5',
      },
      {
        name: 'accessMethod',
        label: 'Access / Work Platform Method',
        type: 'select',
        required: true,
        options: [
          { label: 'Engineered Modular Scaffolding (Green Tagged)', value: 'scaffold' },
          { label: 'Mobile Elevating Work Platform (MEWP / Scissor / Boom)', value: 'MEWP' },
          { label: 'Industrial Ladder (Secured at top and base)', value: 'ladder' },
          { label: 'Industrial Rope Access (IRATA Certified)', value: 'rope' },
        ],
      },
      {
        name: 'fallArrestEquipment',
        label: 'Fall Arrest Equipment Specification',
        type: 'text',
        required: true,
        placeholder: 'e.g. EN 361 Full Body Harness with Twin Shock-Absorbing Lanyard',
      },
      {
        name: 'anchorPointChecked',
        label: 'Certified Anchor Point Verified & Load-Tested',
        type: 'boolean',
        required: true,
        helperText: 'Must verify anchor point is rated for min. 5,000 lbs (22.2 kN) per worker',
      },
      {
        name: 'barricadingBelow',
        label: 'Drop Zone Barricaded & Overhead Warning Signage Posted Below',
        type: 'boolean',
        required: true,
        helperText: 'Strict perimeter barricading below the work radius',
      },
    ],
  },

  ELECTRICAL_LOTO: {
    id: 'ELECTRICAL_LOTO',
    label: 'Electrical / Isolation (LOTO)',
    code: 'LOTO',
    description: 'Work on or near energized or de-energized electrical systems, MCC panels, high-voltage substations, and equipment requiring Lockout/Tagout.',
    badgeColor: 'text-red-700 bg-red-100 border-red-300',
    borderColor: 'border-red-500',
    bgLightColor: 'bg-red-50',
    iconName: 'Zap',
    defaultHazards: [
      'Electrocution / electric shock from live conductors',
      'Arc flash and arc blast explosions',
      'Accidental re-energization while workers are servicing equipment',
      'Residual electrical energy stored in capacitors or inductors',
      'Induced voltage from adjacent live lines',
    ],
    defaultPrecautions: [
      'Equipment positively de-energized and open circuit breaker visually confirmed',
      'Padlocks and standardized Danger Tags installed on every energy isolation point',
      'Multi-lock hasps applied to prevent lockout removal by unauthorized parties',
      'Tested dead with calibrated voltage detector before touch (Live-Dead-Live method)',
      'Portable safety grounding/earthing clusters applied where required',
      'Arc Flash PPE (Face shield, Category rated clothing, insulated gloves) utilized',
    ],
    fields: [
      {
        name: 'equipmentTag',
        label: 'Equipment Tag / MCC Cubicle Number',
        type: 'text',
        required: true,
        placeholder: 'e.g. MCC-01-BKR-12 (Pump 4 Feed)',
      },
      {
        name: 'voltageLevel',
        label: 'Operating Voltage Level',
        type: 'select',
        required: true,
        options: [
          { label: 'Low Voltage (230V Single Phase)', value: '230V' },
          { label: 'Low Voltage (415V Three Phase)', value: '415V' },
          { label: 'Medium Voltage (3.3 kV)', value: '3.3kV' },
          { label: 'Medium Voltage (6.6 kV)', value: '6.6kV' },
          { label: 'High Voltage (11 kV Substation)', value: '11kV' },
          { label: 'Extra High Voltage (33 kV Grid)', value: '33kV' },
        ],
      },
      {
        name: 'lockNumbers',
        label: 'Applied Safety Lock Numbers (comma-separated)',
        type: 'text',
        required: true,
        placeholder: 'e.g. LOK-9041, LOK-9042',
      },
      {
        name: 'tagNumbers',
        label: 'Applied Danger Tag Numbers (comma-separated)',
        type: 'text',
        required: true,
        placeholder: 'e.g. TAG-E-312, TAG-E-313',
      },
      {
        name: 'earthingApplied',
        label: 'Earth / Ground Clamps Applied (Tested & Discharged)',
        type: 'boolean',
        required: true,
        helperText: 'Verification of zero residual charge and grounding installed',
      },
      {
        name: 'testedDeadByWhom',
        label: 'Tested Dead Verified By (Certified Electrical Lead)',
        type: 'text',
        required: true,
        placeholder: 'e.g. S. Ramanathan (Certified Electrical Officer #EL-401)',
      },
    ],
  },

  EXCAVATION: {
    id: 'EXCAVATION',
    label: 'Excavation & Trenching',
    code: 'EXC',
    description: 'Any man-made cut, cavity, trench, or depression in the earth surface formed by earth removal. Demonstrates extensible 5th permit type architecture.',
    badgeColor: 'text-emerald-700 bg-emerald-100 border-emerald-300',
    borderColor: 'border-emerald-500',
    bgLightColor: 'bg-emerald-50',
    iconName: 'Pickaxe',
    defaultHazards: [
      'Cave-in or soil collapse entrapping workers',
      'Striking underground gas pipelines, electrical cables, or fiber optics',
      'Hazardous atmosphere accumulation in deep trenches (> 1.2m)',
      'Water seepage causing soil instability',
      'Falling equipment or vehicles driving near excavation edge',
    ],
    defaultPrecautions: [
      'Underground utility scan (ground penetrating radar / cable locators) completed and signed off',
      'Trench shoring, shielding box, or proper benching angle installed for depth > 1.2m',
      'Excavation spoil piled minimum 1.5 meters back from trench edge',
      'Safe egress ladders placed every 7.5 meters of lateral travel',
      'Atmospheric testing conducted before entry for depths > 1.2 meters',
      'Solid safety railings and stop blocks installed for mobile machinery',
    ],
    fields: [
      {
        name: 'depthInMeters',
        label: 'Excavation Depth (Meters)',
        type: 'number',
        required: true,
        unit: 'meters',
        placeholder: '1.8',
      },
      {
        name: 'undergroundServicesChecked',
        label: 'Underground Cable & Pipe Utility Drawings / Locator Scan Verified',
        type: 'boolean',
        required: true,
        helperText: 'All civil & electrical subterranean maps cross-checked',
      },
      {
        name: 'shoringOrBenchingInstalled',
        label: 'Shoring / Hydraulic Trench Shield / 45° Benching Installed',
        type: 'boolean',
        required: true,
        helperText: 'Required for any trench deeper than 1.2 meters',
      },
      {
        name: 'spoilPlacementDistanceMeters',
        label: 'Spoil & Heavy Equipment Setback Distance (Meters)',
        type: 'number',
        required: true,
        unit: 'meters',
        placeholder: '1.5',
        helperText: 'Must be at least 1.5 meters from trench lip to prevent collapse',
      },
      {
        name: 'gasTestingRequired',
        label: 'Atmospheric Gas Testing Required in Trench (> 1.2m Depth)',
        type: 'boolean',
        required: true,
      },
    ],
  },
};

export function getPermitTypeDefinition(type: string): PermitTypeDefinition {
  const def = PERMIT_TYPES_REGISTRY[type as PermitTypeId];
  if (!def) {
    // Fallback for custom dynamically added permit types
    return {
      id: type as PermitTypeId,
      label: type.replace(/_/g, ' '),
      code: type.slice(0, 3).toUpperCase(),
      description: 'Custom Permit Type',
      badgeColor: 'text-gray-700 bg-gray-100 border-gray-300',
      borderColor: 'border-gray-500',
      bgLightColor: 'bg-gray-50',
      iconName: 'FileText',
      defaultHazards: ['General industrial hazards'],
      defaultPrecautions: ['Standard operating precautions verified'],
      fields: [],
    };
  }
  return def;
}

export function getAllPermitTypes(): PermitTypeDefinition[] {
  return Object.values(PERMIT_TYPES_REGISTRY);
}
